### ISSUE TITLE
[INVALID] x64

### ISSUE THREAD

**Issue by sergeevabc** [gageas/bass_tak2.4#1]
Dear @gageas, could you be so kind to compile x64 version of bass_tak24 as well?

**Comment by gageas** [comment]
I also wanted to use x64 version of BASS, but this is not trivial issue.

bass_tak24 is juat a wrapper of tak_deco_lib.dll (TAK's official decoder), so on x64 env., it requires x64 version of tak_deco_lib.dll which is not released yet...
And because of TAK is not opensourced, we cannot re-compile tak_deco_lib in x64 mode.
(As far as I know, TAK's author uses Pascal and x68 asm optimization, so if code is opened, it may still be difficult to re-compile in x64 mode, I think..)

I also know there is another TAK decoder implementation in libav( http://lists.libav.org/pipermail/libav-commits/2012-December/009219.html ), but I'm not sure where is this code from (revers engineering?)

**Comment by sergeevabc** [comment]
Emailed [Thomas Becker][1] and asked for x64 of ```tak_deco_lib.dll```, never heard back, alas.

[1]: http://www.thbeck.de/Tak/Tak.html

**Comment by gageas** [comment]
I, was a big fun of TAK, began to convert my TAK files into another codec. :cry:
My choice is ALAC. It's portable and now opened. Openness is important...

**Comment by sergeevabc** [comment]
Meh, [ALAC][1] produces so-so compressed ```.m4a``` which is already reserved for lossy [AAC][4] encoded files.
However I agree openness is the way to go, that’s why I have been evaluating [TTA][2] (True Audio) lately. 

```c
Input:
Depeche Mode — Welcome to my world | 4:57 | 192 000 Hz | 24 bit

Output:
178 330 048  TAK   2.4.0  -p2
180 280 855  TTA   2.3
186 051 442  FLAC  1.3.1  -5
187 210 451  M4A   1.61
```
Bonus: slightly outdated yet comprehensive comparison at [Squeezechart][3].

[1]: https://github.com/nu774/qaac/wiki/refalac-usage
[2]: http://tausoft.org/wiki/True_Audio_Codec_Overview
[3]: http://www.squeezechart.com/audio.html
[4]: https://en.wikipedia.org/wiki/Advanced_Audio_Coding
